spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: SpringBatchExampleDB

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local