spring:
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
    fallback-to-system-locale: true

application:
  confirmExit: true
  locale: ru_RU
  resource: "world_geography.csv"
  threshold: 0.6